Repository openAOD/Java-PatternHouse, pull requests merged in 2021-12, with the labels that each got.

#856 Added pattern 16
  Alphabetic Patterns/alphabeticpattern16.java
Labels: SWOC-21

#853 Added pattern 11
  Alphabetic Patterns/alphabeticpattern11.java
Labels: SWOC-21

#855 Added 14,15
  Alphabetic Patterns/alphabeticpattern14.java
  Alphabetic Patterns/alphabeticpattern15.java
Labels: SWOC-21

#854 Added pattern 12,13
  Alphabetic Patterns/alphabeticpattern12.java
Labels: SWOC-21

#859 added from numericpattern179 to numericpattern 189
  Numeric Patterns/numericpattern179.java
  Numeric Patterns/numericpattern180.java
  Numeric Patterns/numericpattern181.java
  Numeric Patterns/numericpattern182.java
  Numeric Patterns/numericpattern183.java
  Numeric Patterns/numericpattern184.java
  Numeric Patterns/numericpattern185.java
  Numeric Patterns/numericpattern186.java
  Numeric Patterns/numericpattern187.java
  Numeric Patterns/numericpattern188.java
  Numeric Patterns/numericpattern189.java
Labels: SWOC-21, beginner

#860 Added code for Pattern 1 to 10
  Pyramid Patterns/pyramidpattern1.java
  Pyramid Patterns/pyramidpattern10.java
  Pyramid Patterns/pyramidpattern2.java
  Pyramid Patterns/pyramidpattern3.java
  Pyramid Patterns/pyramidpattern4.java
  Pyramid Patterns/pyramidpattern5.java
  Pyramid Patterns/pyramidpattern6.java
  Pyramid Patterns/pyramidpattern7.java
  Pyramid Patterns/pyramidpattern8.java
  Pyramid Patterns/pyramidpattern9.java
Labels: SWOC-21, beginner

#861 Added code for Pattern 11 to 25 (Excluding 13 - 17)
  Pyramid Patterns/pyramidpattern11.java
  Pyramid Patterns/pyramidpattern12.java
  Pyramid Patterns/pyramidpattern18.java
  Pyramid Patterns/pyramidpattern19.java
  Pyramid Patterns/pyramidpattern20.java
  Pyramid Patterns/pyramidpattern21.java
  Pyramid Patterns/pyramidpattern22.java
  Pyramid Patterns/pyramidpattern23.java
  Pyramid Patterns/pyramidpattern24.java
  Pyramid Patterns/pyramidpattern25.java
Labels: SWOC-21, beginner

#862 Added code for pyramid pattern 26 to 36 (27 excluded).
  Pyramid Patterns/pyramidpattern26.java
  Pyramid Patterns/pyramidpattern28.java
  Pyramid Patterns/pyramidpattern29.java
  Pyramid Patterns/pyramidpattern30.java
  Pyramid Patterns/pyramidpattern31.java
  Pyramid Patterns/pyramidpattern32.java
  Pyramid Patterns/pyramidpattern33.java
  Pyramid Patterns/pyramidpattern34.java
  Pyramid Patterns/pyramidpattern35.java
  Pyramid Patterns/pyramidpattern36.java
Labels: SWOC-21, beginner

#863 added numericpattern190 to 212
  Numeric Patterns/numericpattern190.java
  Numeric Patterns/numericpattern191.java
  Numeric Patterns/numericpattern192.java
  Numeric Patterns/numericpattern193.java
  Numeric Patterns/numericpattern194.java
  Numeric Patterns/numericpattern195.java
  Numeric Patterns/numericpattern196.java
  Numeric Patterns/numericpattern197.java
  Numeric Patterns/numericpattern198.java
  Numeric Patterns/numericpattern199.java
  Numeric Patterns/numericpattern200.java
  Numeric Patterns/numericpattern201.java
  Numeric Patterns/numericpattern202.java
  Numeric Patterns/numericpattern203.java
  Numeric Patterns/numericpattern204.java
  Numeric Patterns/numericpattern205.java
  Numeric Patterns/numericpattern206.java
  Numeric Patterns/numericpattern207.java
  Numeric Patterns/numericpattern208.java
  Numeric Patterns/numericpattern209.java
  Numeric Patterns/numericpattern210.java
  Numeric Patterns/numericpattern211.java
  Numeric Patterns/numericpattern212.java
Labels: SWOC-21, easy

#864 Added code for pyramid pattern 37 to 45 (27 included).
  Pyramid Patterns/pyramidpattern27.java
  Pyramid Patterns/pyramidpattern37.java
  Pyramid Patterns/pyramidpattern38.java
  Pyramid Patterns/pyramidpattern39.java
  Pyramid Patterns/pyramidpattern40.java
  Pyramid Patterns/pyramidpattern41.java
  Pyramid Patterns/pyramidpattern42.java
  Pyramid Patterns/pyramidpattern43.java
  Pyramid Patterns/pyramidpattern44.java
  Pyramid Patterns/pyramidpattern45.java
Labels: SWOC-21, beginner

#865 Added code for pyramid pattern from 46 to 55.
  Pyramid Patterns/pyramidpattern46.java
  Pyramid Patterns/pyramidpattern47.java
  Pyramid Patterns/pyramidpattern48.java
  Pyramid Patterns/pyramidpattern49.java
  Pyramid Patterns/pyramidpattern50.java
  Pyramid Patterns/pyramidpattern51.java
  Pyramid Patterns/pyramidpattern52.java
  Pyramid Patterns/pyramidpattern53.java
  Pyramid Patterns/pyramidpattern54.java
  Pyramid Patterns/pyramidpattern55.java
Labels: SWOC-21, beginner

#866 solved issues #730 to #740
  Numeric Patterns/numericpattern213.java
  Numeric Patterns/numericpattern214.java
  Numeric Patterns/numericpattern215.java
  Numeric Patterns/numericpattern216.java
  Numeric Patterns/numericpattern217.java
  Numeric Patterns/numericpattern218.java
  Numeric Patterns/numericpattern219.java
  Numeric Patterns/numericpattern220.java
  Numeric Patterns/numericpattern221.java
  Numeric Patterns/numericpattern222.java
  Numeric Patterns/numericpattern223.java
  Numeric Patterns/pattern33.java
Labels: SWOC-21, beginner

#867 Added code for pyramid pattern 56 to 75.
  Pyramid Patterns/pyramidpattern56.java
  Pyramid Patterns/pyramidpattern57.java
  Pyramid Patterns/pyramidpattern58.java
  Pyramid Patterns/pyramidpattern59.java
  Pyramid Patterns/pyramidpattern60.java
  Pyramid Patterns/pyramidpattern61.java
  Pyramid Patterns/pyramidpattern62.java
  Pyramid Patterns/pyramidpattern63.java
  Pyramid Patterns/pyramidpattern64.java
  Pyramid Patterns/pyramidpattern65.java
  Pyramid Patterns/pyramidpattern66.java
  Pyramid Patterns/pyramidpattern67.java
  Pyramid Patterns/pyramidpattern68.java
  Pyramid Patterns/pyramidpattern69.java
  Pyramid Patterns/pyramidpattern70.java
  Pyramid Patterns/pyramidpattern71.java
  Pyramid Patterns/pyramidpattern72.java
  Pyramid Patterns/pyramidpattern73.java
  Pyramid Patterns/pyramidpattern74.java
  Pyramid Patterns/pyramidpattern75.java
Labels: SWOC-21, easy

#868 Added code for pyramid pattern from 76 to 93.
  Pyramid Patterns/pyramidpattern76.java
  Pyramid Patterns/pyramidpattern77.java
  Pyramid Patterns/pyramidpattern78.java
  Pyramid Patterns/pyramidpattern79.java
  Pyramid Patterns/pyramidpattern80.java
  Pyramid Patterns/pyramidpattern81.java
  Pyramid Patterns/pyramidpattern82.java
  Pyramid Patterns/pyramidpattern83.java
  Pyramid Patterns/pyramidpattern84.java
  Pyramid Patterns/pyramidpattern85.java
  Pyramid Patterns/pyramidpattern86.java
  Pyramid Patterns/pyramidpattern87.java
  Pyramid Patterns/pyramidpattern88.java
  Pyramid Patterns/pyramidpattern89.java
  Pyramid Patterns/pyramidpattern90.java
  Pyramid Patterns/pyramidpattern91.java
  Pyramid Patterns/pyramidpattern92.java
  Pyramid Patterns/pyramidpattern93.java
  Symbol Patterns/symbolpattern1.java
  Symbol Patterns/symbolpattern2.java
Labels: SWOC-21, easy

#857 Added patterns 17,18,20
  Alphabetic Patterns/alphabeticpattern17.java
  Alphabetic Patterns/alphabeticpattern18.java
  Alphabetic Patterns/alphabeticpattern20.java
  Numeric Patterns/numericpattern1.java
  numericpattern11.java
  numericpattern2.java
  numericpattern3.java
  numericpattern4.java
  numericpattern5.java
  numericpattern54.java
Labels: SWOC-21, beginner

#869 added numericpattern224 to 234
  Numeric Patterns/numericpattern224.java
  Numeric Patterns/numericpattern225.java
  Numeric Patterns/numericpattern226.java
  Numeric Patterns/numericpattern227.java
  Numeric Patterns/numericpattern228.java
  Numeric Patterns/numericpattern229.java
  Numeric Patterns/numericpattern230.java
  Numeric Patterns/numericpattern231.java
  Numeric Patterns/numericpattern232.java
  Numeric Patterns/numericpattern233.java
  Numeric Patterns/numericpattern234.java
Labels: SWOC-21, beginner

#870 added numericpattern235 to 245
  Numeric Patterns/numericpattern235.java
  Numeric Patterns/numericpattern236.java
  Numeric Patterns/numericpattern237.java
  Numeric Patterns/numericpattern238.java
  Numeric Patterns/numericpattern239.java
  Numeric Patterns/numericpattern240.java
  Numeric Patterns/numericpattern241.java
  Numeric Patterns/numericpattern242.java
  Numeric Patterns/numericpattern243.java
  Numeric Patterns/numericpattern244.java
  Numeric Patterns/numericpattern245.java
Labels: SWOC-21, beginner

#871 SWOC 2.0 : Fixed Alphabetic Patterns
  Alphabetic Patterns/alphabeticpattern32.java
  Alphabetic Patterns/alphabeticpattern33.java
  Alphabetic Patterns/alphabeticpattern34.java
  Alphabetic Patterns/alphabeticpattern35.java
  Alphabetic Patterns/alphabeticpattern36.java
  Alphabetic Patterns/alphabeticpattern37.java
  Alphabetic Patterns/alphabeticpattern38.java
  Alphabetic Patterns/alphabeticpattern40.java
  Alphabetic Patterns/alphabeticpattern41.java
  Alphabetic Patterns/alphabeticpattern43.java
Labels: SWOC-21, beginner

#872 Added numericpattern 48 to 58 and numericpattern 93 to 102
  Numeric Patterns/numericpattern100.java
  Numeric Patterns/numericpattern101.java
  Numeric Patterns/numericpattern102.java
  Numeric Patterns/numericpattern48.java
  Numeric Patterns/numericpattern49.java
  Numeric Patterns/numericpattern50.java
  Numeric Patterns/numericpattern51.java
  Numeric Patterns/numericpattern52.java
  Numeric Patterns/numericpattern53.java
  Numeric Patterns/numericpattern55.java
  Numeric Patterns/numericpattern56.java
  Numeric Patterns/numericpattern57.java
  Numeric Patterns/numericpattern58.java
  Numeric Patterns/numericpattern93.java
  Numeric Patterns/numericpattern94.java
  Numeric Patterns/numericpattern95.java
  Numeric Patterns/numericpattern96.java
  Numeric Patterns/numericpattern97.java
  Numeric Patterns/numericpattern98.java
  Numeric Patterns/numericpattern99.java
Labels: SWOC-21, easy

#873 SWOC 2.0 : Fixed Alphabetic Patterns
  Alphabetic Patterns/alphabeticpattern42.java
  Alphabetic Patterns/alphabeticpattern44.java
  Alphabetic Patterns/alphabeticpattern45.java
  Alphabetic Patterns/alphabeticpattern46.java
  Alphabetic Patterns/alphabeticpattern47.java
  Alphabetic Patterns/alphabeticpattern48.java
  Alphabetic Patterns/alphabeticpattern49.java
  Alphabetic Patterns/alphabeticpattern50.java
  Alphabetic Patterns/alphabeticpattern51.java
  Alphabetic Patterns/alphabeticpattern52.java
Labels: SWOC-21, beginner

#874 SWOC 2.0 : Fixed Alphabetic Patterns & Numeric Patterns
  Alphabetic Patterns/alphabeticpattern53.java
  Alphabetic Patterns/alphabeticpattern55.java
  Alphabetic Patterns/alphabeticpattern56.java
  Alphabetic Patterns/alphabeticpattern57.java
  Alphabetic Patterns/alphabeticpattern58.java
  Alphabetic Patterns/alphabeticpattern59.java
  Alphabetic Patterns/alphabeticpattern60.java
  Alphabetic Patterns/alphabeticpattern61.java
  Alphabetic Patterns/alphabeticpattern62.java
  Alphabetic Patterns/alphabeticpattern63.java
  Alphabetic Patterns/alphabeticpattern64.java
  Alphabetic Patterns/alphabeticpattern65.java
  Numeric Patterns/numericpattern103.java
  Numeric Patterns/numericpattern104.java
  Numeric Patterns/numericpattern105.java
  Numeric Patterns/numericpattern106.java
  Numeric Patterns/numericpattern107.java
  Numeric Patterns/numericpattern108.java
  Numeric Patterns/numericpattern109.java
  Numeric Patterns/numericpattern110.java
Labels: SWOC-21, easy

#875 SWOC 2.0 : Fixed Numeric Patterns
  Numeric Patterns/numericpattern112.java
  Numeric Patterns/numericpattern113.java
  Numeric Patterns/numericpattern114.java
  Numeric Patterns/numericpattern115.java
  Numeric Patterns/numericpattern116.java
  Numeric Patterns/numericpattern117.java
  Numeric Patterns/numericpattern118.java
  Numeric Patterns/numericpattern119.java
  Numeric Patterns/numericpattern120.java
  Numeric Patterns/numericpattern121.java
Labels: SWOC-21, beginner

#877 SWOC 2.0 : Fixed Symbol Patterns
  Symbol Patterns/symbolpattern21.java
  Symbol Patterns/symbolpattern22.java
  Symbol Patterns/symbolpattern23.java
  Symbol Patterns/symbolpattern24.java
  Symbol Patterns/symbolpattern25.java
  Symbol Patterns/symbolpattern26.java
  Symbol Patterns/symbolpattern27.java
  Symbol Patterns/symbolpattern28.java
  Symbol Patterns/symbolpattern29.java
  Symbol Patterns/symbolpattern30.java
Labels: SWOC-21, beginner

#879 Symbol pattern -106 to 116
  Symbol Patterns/symbolpattern106.java
  Symbol Patterns/symbolpattern107.java
  Symbol Patterns/symbolpattern108.java
  Symbol Patterns/symbolpattern109.java
  Symbol Patterns/symbolpattern110.java
  Symbol Patterns/symbolpattern111.java
  Symbol Patterns/symbolpattern112.java
  Symbol Patterns/symbolpattern113.java
  Symbol Patterns/symbolpattern114.java
  Symbol Patterns/symbolpattern115.java
  Symbol Patterns/symbolpattern116.java
Labels: SWOC-21, beginner

#878 SWOC 2.0 : Fixed Symbol Patterns & Numeric Patterns
  Numeric Patterns/numericpattern122.java
  Numeric Patterns/numericpattern123.java
  Symbol Patterns/symbolpattern32.java
  Symbol Patterns/symbolpattern33.java
  Symbol Patterns/symbolpattern34.java
  Symbol Patterns/symbolpattern35.java
  Symbol Patterns/symbolpattern36.java
  Symbol Patterns/symbolpattern37.java
  Symbol Patterns/symbolpattern38.java
  Symbol Patterns/symbolpattern39.java
  Symbol Patterns/symbolpattern40.java
  Symbol Patterns/symbolpattern41.java
  Symbol Patterns/symbolpattern42.java
  Symbol Patterns/symbolpattern43.java
  Symbol Patterns/symbolpattern44.java
  Symbol Patterns/symbolpattern45.java
  Symbol Patterns/symbolpattern46.java
  Symbol Patterns/symbolpattern47.java
  Symbol Patterns/symbolpattern48.java
  Symbol Patterns/symbolpattern49.java
  Symbol Patterns/symbolpattern50.java
  Symbol Patterns/symbolpattern51.java
  Symbol Patterns/symbolpattern52.java
  Symbol Patterns/symbolpattern53.java
  Symbol Patterns/symbolpattern54.java
  Symbol Patterns/symbolpattern55.java
  Symbol Patterns/symbolpattern56.java
  Symbol Patterns/symbolpattern57.java
  Symbol Patterns/symbolpattern58.java
  Symbol Patterns/symbolpattern59.java
  Symbol Patterns/symbolpattern60.java
  Symbol Patterns/symbolpattern61.java
  Symbol Patterns/symbolpattern62.java
  Symbol Patterns/symbolpattern63.java
  Symbol Patterns/symbolpattern64.java
  Symbol Patterns/symbolpattern65.java
  Symbol Patterns/symbolpattern66.java
  Symbol Patterns/symbolpattern67.java
  Symbol Patterns/symbolpattern68.java
  Symbol Patterns/symbolpattern69.java
  Symbol Patterns/symbolpattern70.java
Labels: SWOC-21, hard
