Repository openAOD/Java-PatternHouse, pull requests merged in 2022-01, with the labels that each got.

#876 added numericpattern247 to 254
  Numeric Patterns/numericpattern246.java
  Numeric Patterns/numericpattern247.java
  Numeric Patterns/numericpattern248.java
  Numeric Patterns/numericpattern249.java
  Numeric Patterns/numericpattern250.java
  Numeric Patterns/numericpattern251.java
  Numeric Patterns/numericpattern252.java
  Numeric Patterns/numericpattern253.java
  Numeric Patterns/numericpattern254.java
  Numeric Patterns/numericpattern256.java
Labels: SWOC-21, beginner

#881 Code for String Pattern (1-15) and Alphabetic Pattern (5-8, 31, 39, 72-96) in Java.
  Alphabetic Patterns/alphabeticpattern31.java
  Alphabetic Patterns/alphabeticpattern39.java
  Alphabetic Patterns/alphabeticpattern5.java
  Alphabetic Patterns/alphabeticpattern6.java
  Alphabetic Patterns/alphabeticpattern7.java
  Alphabetic Patterns/alphabeticpattern72.java
  Alphabetic Patterns/alphabeticpattern73.java
  Alphabetic Patterns/alphabeticpattern74.java
  Alphabetic Patterns/alphabeticpattern75.java
  Alphabetic Patterns/alphabeticpattern76.java
  Alphabetic Patterns/alphabeticpattern77.java
  Alphabetic Patterns/alphabeticpattern78.java
  Alphabetic Patterns/alphabeticpattern79.java
  Alphabetic Patterns/alphabeticpattern8.java
  Alphabetic Patterns/alphabeticpattern80.java
  Alphabetic Patterns/alphabeticpattern81.java
  Alphabetic Patterns/alphabeticpattern82,java
  Alphabetic Patterns/alphabeticpattern83.java
  Alphabetic Patterns/alphabeticpattern84.java
  Alphabetic Patterns/alphabeticpattern85.java
  Alphabetic Patterns/alphabeticpattern86.java
  Alphabetic Patterns/alphabeticpattern87.java
  Alphabetic Patterns/alphabeticpattern88.java
  Alphabetic Patterns/alphabeticpattern89.java
  Alphabetic Patterns/alphabeticpattern90.java
  Alphabetic Patterns/alphabeticpattern91.java
  Alphabetic Patterns/alphabeticpattern92.java
  Alphabetic Patterns/alphabeticpattern93.java
  Alphabetic Patterns/alphabeticpattern94.java
  Alphabetic Patterns/alphabeticpattern95.java
  Alphabetic Patterns/alphabeticpattern96.java
  String Patterns/stringpattern1.java
  String Patterns/stringpattern10.java
  String Patterns/stringpattern11.java
  String Patterns/stringpattern12.java
  String Patterns/stringpattern13.java
  String Patterns/stringpattern14.java
  String Patterns/stringpattern15.java
  String Patterns/stringpattern2.java
  String Patterns/stringpattern3.java
  String Patterns/stringpattern4.java
  String Patterns/stringpattern5.java
  String Patterns/stringpattern6.java
  String Patterns/stringpattern7.java
  String Patterns/stringpattern8.java
  String Patterns/stringpattern9.java
Labels: SWOC-21, hard

#883 20 patterns added Alphabetic and Numeric
  Alphabetic Patterns/alphabeticpatern109.java
  Alphabetic Patterns/alphabeticpattern101.java
  Alphabetic Patterns/alphabeticpattern102.java
  Alphabetic Patterns/alphabeticpattern103.java
  Alphabetic Patterns/alphabeticpattern104.java
  Alphabetic Patterns/alphabeticpattern105.java
  Alphabetic Patterns/alphabeticpattern106.java
  Alphabetic Patterns/alphabeticpattern107.java
  Alphabetic Patterns/alphabeticpattern108.java
  Alphabetic Patterns/alphabeticpattern110.java
  Numeric Patterns/numericpattern260.java
  Numeric Patterns/numericpattern261.java
  Numeric Patterns/numericpattern262.java
  Numeric Patterns/numericpattern263.java
  Numeric Patterns/numericpattern271.java
  Numeric Patterns/numericpattern272.java
  Numeric Patterns/numericpattern273.java
  Numeric Patterns/numericpattern283.java
  Numeric Patterns/numericpattern317.java
  Numeric Patterns/numericpattern318.java
Labels: SWOC-21, easy

#884 SWOC 2.0 :Fixed Numeric Patterns
  Numeric Patterns/numericpattern16.java
  Numeric Patterns/numericpattern17.java
  Numeric Patterns/numericpattern18.java
  Numeric Patterns/numericpattern19.java
  Numeric Patterns/numericpattern20.java
  Numeric Patterns/numericpattern21.java
  Numeric Patterns/numericpattern22.java
  Numeric Patterns/numericpattern23.java
  Numeric Patterns/numericpattern24.java
  Numeric Patterns/numericpattern25.java
Labels: SWOC-21, beginner

#882 Alphabetic Pattern in Java (97-100, 113, 114, 118-122, 134-139).
  Alphabetic Patterns/alphabeticpattern100.java
  Alphabetic Patterns/alphabeticpattern113.java
  Alphabetic Patterns/alphabeticpattern114.java
  Alphabetic Patterns/alphabeticpattern118.java
  Alphabetic Patterns/alphabeticpattern119.java
  Alphabetic Patterns/alphabeticpattern120.java
  Alphabetic Patterns/alphabeticpattern121.java
  Alphabetic Patterns/alphabeticpattern122.java
  Alphabetic Patterns/alphabeticpattern134.java
  Alphabetic Patterns/alphabeticpattern135.java
  Alphabetic Patterns/alphabeticpattern136.java
  Alphabetic Patterns/alphabeticpattern137.java
  Alphabetic Patterns/alphabeticpattern138.java
  Alphabetic Patterns/alphabeticpattern139.java
  Alphabetic Patterns/alphabeticpattern97.java
  Alphabetic Patterns/alphabeticpattern98.java
  Alphabetic Patterns/alphabeticpattern99.java
Labels: SWOC-21, beginner

#889 SWOC 2.0 :Fixed Numeric Patterns
  Numeric Patterns/numericpattern61.java
  Numeric Patterns/numericpattern62.java
  Numeric Patterns/numericpattern63.java
  Numeric Patterns/numericpattern64.java
  Numeric Patterns/numericpattern65.java
  Numeric Patterns/numericpattern66.java
  Numeric Patterns/numericpattern67.java
  Numeric Patterns/numericpattern68.java
  Numeric Patterns/numericpattern69.java
  Numeric Patterns/numericpattern70.java
Labels: SWOC-21, beginner

#890 Alphabetic and Numeric patterns added
  Alphabetic Patterns/alphabeticpattern111.java
  Alphabetic Patterns/alphabeticpattern112.java
  Alphabetic Patterns/alphabeticpattern115.java
  Alphabetic Patterns/alphabeticpattern116.java
  Alphabetic Patterns/alphabeticpattern117.java
  Alphabetic Patterns/alphabeticpattern123.java
  Alphabetic Patterns/alphabeticpattern124.java
  Alphabetic Patterns/alphabeticpattern125.java
  Alphabetic Patterns/alphabeticpattern126.java
  Alphabetic Patterns/alphabeticpattern127.java
  Alphabetic Patterns/alphabeticpattern128.java
  Alphabetic Patterns/alphabeticpattern129.java
  Alphabetic Patterns/alphabeticpattern130.java
  Alphabetic Patterns/alphabeticpattern131.java
  Alphabetic Patterns/alphabeticpattern69.java
  Alphabetic Patterns/alphabeticpattern71.java
  Numeric Patterns/numericpattern167.java
  Numeric Patterns/numericpattern168.java
  Numeric Patterns/numericpattern169.java
  Numeric Patterns/numericpattern264.java
  Numeric Patterns/numericpattern265.java
  Numeric Patterns/numericpattern266.java
  Numeric Patterns/numericpattern267.java
  Numeric Patterns/numericpattern268.java
  Numeric Patterns/numericpattern269.java
  Numeric Patterns/numericpattern270.java
  Numeric Patterns/numericpattern274.java
  Numeric Patterns/numericpattern275.java
  Numeric Patterns/numericpattern280.java
  Numeric Patterns/numericpattern281.java
  Numeric Patterns/numericpattern282.java
  Numeric Patterns/numericpattern284.java
  Numeric Patterns/numericpattern285.java
  Numeric Patterns/numericpattern289.java
  Numeric Patterns/numericpattern290.java
  Numeric Patterns/numericpattern291.java
  Numeric Patterns/numericpattern292.java
  Numeric Patterns/numericpattern293.java
  Numeric Patterns/numericpattern315.java
  Numeric Patterns/numericpattern316.java
Labels: SWOC-21, hard

#888 Alphabetic Pattern 66-68, 70, 132, 133, 166-191
  Alphabetic Patterns/alphabeticpattern132.java
  Alphabetic Patterns/alphabeticpattern133.java
  Alphabetic Patterns/alphabeticpattern166.java
  Alphabetic Patterns/alphabeticpattern167.java
  Alphabetic Patterns/alphabeticpattern168.java
  Alphabetic Patterns/alphabeticpattern169.java
  Alphabetic Patterns/alphabeticpattern170.java
  Alphabetic Patterns/alphabeticpattern171.java
  Alphabetic Patterns/alphabeticpattern172.java
  Alphabetic Patterns/alphabeticpattern173.java
  Alphabetic Patterns/alphabeticpattern174.java
  Alphabetic Patterns/alphabeticpattern175.java
  Alphabetic Patterns/alphabeticpattern176.java
  Alphabetic Patterns/alphabeticpattern177.java
  Alphabetic Patterns/alphabeticpattern178.java
  Alphabetic Patterns/alphabeticpattern179.java
  Alphabetic Patterns/alphabeticpattern180.java
  Alphabetic Patterns/alphabeticpattern181.java
  Alphabetic Patterns/alphabeticpattern66.java
  Alphabetic Patterns/alphabeticpattern67.java
  Alphabetic Patterns/alphabeticpattern68.java
  Alphabetic Patterns/alphabeticpattern70.java
Labels: SWOC-21, easy

#895 Numeric Patterns added
  Numeric Patterns/numericpattern125.java
  Numeric Patterns/numericpattern134.java
  Numeric Patterns/numericpattern135.java
  Numeric Patterns/numericpattern136.java
  Numeric Patterns/numericpattern137.java
  Numeric Patterns/numericpattern138.java
  Numeric Patterns/numericpattern153.java
  Numeric Patterns/numericpattern154.java
  Numeric Patterns/numericpattern155.java
  Numeric Patterns/numericpattern156.java
  Numeric Patterns/numericpattern157.java
  Numeric Patterns/numericpattern158.java
  Numeric Patterns/numericpattern159.java
  Numeric Patterns/numericpattern160.java
  Numeric Patterns/numericpattern161.java
  Numeric Patterns/numericpattern163.java
  Numeric Patterns/numericpattern164.java
  Numeric Patterns/numericpattern165.java
  Numeric Patterns/numericpattern166.java
  Numeric Patterns/numericpattern170.java
Labels: SWOC-21, easy

#894 Alphabetic and Numeric Pattern in Java
  Alphabetic Patterns/alphabeticpattern184.java
  Alphabetic Patterns/alphabeticpattern185.java
  Alphabetic Patterns/alphabeticpattern186.java
  Alphabetic Patterns/alphabeticpattern187.java
  Alphabetic Patterns/alphabeticpattern189.java
  Alphabetic Patterns/alphabeticpattern190.java
  Alphabetic Patterns/alphabeticpattern191.java
  Numeric Patterns/numericpattern124.java
  Numeric Patterns/numericpattern126.java
  Numeric Patterns/numericpattern127.java
  Numeric Patterns/numericpattern128.java
  Numeric Patterns/numericpattern129.java
  Numeric Patterns/numericpattern130.java
  Numeric Patterns/numericpattern131.java
  Numeric Patterns/numericpattern132.java
  Numeric Patterns/numericpattern133.java
  Numeric Patterns/numericpattern139.java
  Numeric Patterns/numericpattern140.java
  Numeric Patterns/numericpattern141.java
  Numeric Patterns/numericpattern142.java
  Numeric Patterns/numericpattern143.java
  Numeric Patterns/numericpattern144.java
  Numeric Patterns/numericpattern145.java
  Numeric Patterns/numericpattern146.java
  Numeric Patterns/numericpattern147.java
  Numeric Patterns/numericpattern148.java
  Numeric Patterns/numericpattern149.java
  Numeric Patterns/numericpattern150.java
  Numeric Patterns/numericpattern151.java
  Numeric Patterns/numericpattern71.java
  Numeric Patterns/numericpattern72.java
  Numeric Patterns/numericpattern73.java
  Numeric Patterns/numericpattern74.java
  Numeric Patterns/numericpattern75.java
  Numeric Patterns/numericpattern79.java
  Numeric Patterns/numericpattern87.java
  Numeric Patterns/numericpattern88.java
  Numeric Patterns/numericpattern89.java
  Numeric Patterns/numericpattern90.java
  Numeric Patterns/numericpattern91.java
Labels: SWOC-21, hard

#899 Numeric Patterns added
  Numeric Patterns/numericpattern172.java
  Numeric Patterns/numericpattern173.java
  Numeric Patterns/numericpattern174.java
  Numeric Patterns/numericpattern177.java
  Numeric Patterns/numericpattern178.java
  Numeric Patterns/numericpattern77.java
  Numeric Patterns/numericpattern83.java
  Numeric Patterns/numericpattern84.java
  Numeric Patterns/numericpattern85.java
  Numeric Patterns/numericpattern86.java
Labels: SWOC-21, beginner

#900 Create numericpattern38.java
  Alphabetic Patterns/alphabeticpattern182.java
  Alphabetic Patterns/alphabeticpattern183.java
  Alphabetic Patterns/alphabeticpattern188.java
  Numeric Patterns/numericpattern152.java
  Numeric Patterns/numericpattern171.java
  Numeric Patterns/numericpattern175.java
  Numeric Patterns/numericpattern176.java
  Numeric Patterns/numericpattern286.java
  Numeric Patterns/numericpattern287.java
  Numeric Patterns/numericpattern294.java
  Numeric Patterns/numericpattern303.java
  Numeric Patterns/numericpattern304.java
  Numeric Patterns/numericpattern305.java
  Numeric Patterns/numericpattern306.java
  Numeric Patterns/numericpattern307.java
  Numeric Patterns/numericpattern308.java
  Numeric Patterns/numericpattern309.java
  Numeric Patterns/numericpattern311.java
  Numeric Patterns/numericpattern312.java
  Numeric Patterns/numericpattern313.java
  Numeric Patterns/numericpattern314.java
  Numeric Patterns/numericpattern319.java
  Numeric Patterns/numericpattern321.java
  Numeric Patterns/numericpattern322.java
  Numeric Patterns/numericpattern323.java
  Numeric Patterns/numericpattern327.java
  Numeric Patterns/numericpattern38.java
  Numeric Patterns/numericpattern42.java
  Numeric Patterns/numericpattern76.java
  Numeric Patterns/numericpattern78.java
Labels: SWOC-21, medium

#897 Numeric Pattern 324
  Alphabetic Patterns/alphabeticpattern148.java
  Alphabetic Patterns/alphabeticpattern149.java
  Alphabetic Patterns/alphabeticpattern150.java
  Alphabetic Patterns/alphabeticpattern151.java
  Alphabetic Patterns/alphabeticpattern152.java
  Alphabetic Patterns/alphabeticpattern153.java
  Alphabetic Patterns/alphabeticpattern154.java
  Alphabetic Patterns/alphabeticpattern155.java
  Numeric Patterns/numericpattern324.java
  Numeric Patterns/numericpattern325.java
Labels: SWOC-21, beginner

#901 Create numericpattern255.java
  Numeric Patterns/numericpattern255.java
  Numeric Patterns/numericpattern257.java
  Numeric Patterns/numericpattern276.java
  Numeric Patterns/numericpattern277.java
  Numeric Patterns/numericpattern278.java
  Numeric Patterns/numericpattern279.java
  Numeric Patterns/numericpattern310.java
  Numeric Patterns/numericpattern320.java
  Numeric Patterns/numericpattern326.java
  Numeric Patterns/numericpattern328.java
Labels: SWOC-21, beginner

#902 40 symbol patterns added
  Symbol Patterns/symbolpattern10.java
  Symbol Patterns/symbolpattern11.java
  Symbol Patterns/symbolpattern12.java
  Symbol Patterns/symbolpattern13.java
  Symbol Patterns/symbolpattern14.java
  Symbol Patterns/symbolpattern15.java
  Symbol Patterns/symbolpattern16.java
  Symbol Patterns/symbolpattern17.java
  Symbol Patterns/symbolpattern18.java
  Symbol Patterns/symbolpattern19.java
  Symbol Patterns/symbolpattern20.java
  Symbol Patterns/symbolpattern3.java
  Symbol Patterns/symbolpattern31.java
  Symbol Patterns/symbolpattern4.java
  Symbol Patterns/symbolpattern5.java
  Symbol Patterns/symbolpattern6.java
  Symbol Patterns/symbolpattern7.java
  Symbol Patterns/symbolpattern71.java
  Symbol Patterns/symbolpattern72.java
  Symbol Patterns/symbolpattern73.java
  Symbol Patterns/symbolpattern74.java
  Symbol Patterns/symbolpattern75.java
  Symbol Patterns/symbolpattern76.java
  Symbol Patterns/symbolpattern77.java
  Symbol Patterns/symbolpattern78.java
  Symbol Patterns/symbolpattern79.java
  Symbol Patterns/symbolpattern8.java
  Symbol Patterns/symbolpattern80.java
  Symbol Patterns/symbolpattern81.java
  Symbol Patterns/symbolpattern82.java
  Symbol Patterns/symbolpattern83.java
  Symbol Patterns/symbolpattern84.java
  Symbol Patterns/symbolpattern85.java
  Symbol Patterns/symbolpattern86.java
  Symbol Patterns/symbolpattern87.java
  Symbol Patterns/symbolpattern88.java
  Symbol Patterns/symbolpattern89.java
  Symbol Patterns/symbolpattern9.java
  Symbol Patterns/symbolpattern90.java
  Symbol Patterns/symbolpattern91.java
Labels: SWOC-21, hard

#903 40 symbol patterns added
  Symbol Patterns/symbolpattern100.java
  Symbol Patterns/symbolpattern101.java
  Symbol Patterns/symbolpattern102.java
  Symbol Patterns/symbolpattern103.java
  Symbol Patterns/symbolpattern104.java
  Symbol Patterns/symbolpattern105.java
  Symbol Patterns/symbolpattern117.java
  Symbol Patterns/symbolpattern118.java
  Symbol Patterns/symbolpattern119.java
  Symbol Patterns/symbolpattern120.java
  Symbol Patterns/symbolpattern121.java
  Symbol Patterns/symbolpattern122.java
  Symbol Patterns/symbolpattern123.java
  Symbol Patterns/symbolpattern124.java
  Symbol Patterns/symbolpattern125.java
  Symbol Patterns/symbolpattern126.java
  Symbol Patterns/symbolpattern127.java
  Symbol Patterns/symbolpattern128.java
  Symbol Patterns/symbolpattern129.java
  Symbol Patterns/symbolpattern130.java
  Symbol Patterns/symbolpattern131.java
  Symbol Patterns/symbolpattern132.java
  Symbol Patterns/symbolpattern133.java
  Symbol Patterns/symbolpattern134.java
  Symbol Patterns/symbolpattern135.java
  Symbol Patterns/symbolpattern136.java
  Symbol Patterns/symbolpattern137.java
  Symbol Patterns/symbolpattern138.java
  Symbol Patterns/symbolpattern139.java
  Symbol Patterns/symbolpattern140.java
  Symbol Patterns/symbolpattern141.java
  Symbol Patterns/symbolpattern142.java
  Symbol Patterns/symbolpattern92.java
  Symbol Patterns/symbolpattern93.java
  Symbol Patterns/symbolpattern94.java
  Symbol Patterns/symbolpattern95.java
  Symbol Patterns/symbolpattern96.java
  Symbol Patterns/symbolpattern97.java
  Symbol Patterns/symbolpattern98.java
  Symbol Patterns/symbolpattern99.java
Labels: SWOC-21, hard
